### ISSUE TITLE
Flyout menu shows that I'm logged in, but publish attempt says otherwise.

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#126] opened 2016-11-28 22:45 UTC
On my Android device, I ran into an issue where the Flyout menu shows that I'm logged in to the application but when I try to publish new or updated services I get an error message that I need to be logged in to publish points.

It appears that at some point my session times out and I'm no longer logged into the app even though the fly out menu shows that I'm still logged in. 

1. These two areas should not contradict each other. 
2. How are sessions maintained in the app? Should we be keeping a user authenticated once they login until their credentials have changed? It seems that sessions end very frequently while most mobile apps keep you logged on for a long time.

**Comment by samfalconer** [comment] 2017-02-12 22:06
Moving to https://github.com/Tour-de-Force/btc-app-server/issues/47 and closing.

**Comment by jsieber-aca** [comment] 2017-03-09 18:43
I had this happen today when testing on the web version.

**Comment by jsieber-aca** [comment] 2017-03-09 19:28
Happened multiple times while I was testing today.

**Comment by samfalconer** [comment] 2017-03-25 23:08
I thought this was being caused by #185 , but having fixed that I don't think so now.

**Comment by samfalconer** [comment] 2017-03-31 01:34
Resolved in https://github.com/Tour-de-Force/btc-app-server/issues/47

**Closed by samfalconer** 2017-03-31 01:34 UTC
Labels: bug, Priority: High, usability
